language: python
cache: pip
sudo: false
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - 'pypy3.5'

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install: pip install .

script: python run_tests.py
