language: python
cache: pip
sudo: false
python:
  - '2.7'
  - '3.6'
  - '3.7'
  - '3.8'
  - 'pypy3.5'

matrix:
  include:
    - python: 3.7
      dist: bionic
      sudo: true

install: pip install .

script: python run_tests.py
